const cards: Object = {
  main:[
    {
      word: 'Animal',
      translation: 'Животные',
      image: './img/main/animal.jpg',
      audio: undefined,
    },
    {
      word: 'Clothes',
      translation: 'Одежда',
      image: './img/main/clothes.jpg',
      audio: undefined,
    },
    {
      word: 'Food',
      translation: 'Еда',
      image: './img/main/food.jpg',
      audio: undefined,
    },
    {
      word: 'School',
      translation: 'Школа',
      image: './img/main/school.jpg',
      audio: undefined,
    },
    {
      word: 'Nature',
      translation: 'Природа',
      image: './img/main/nature.jpg',
      audio: undefined,
    },
    {
      word: 'Furniture',
      translation: 'Мебель',
      image: './img/main/furniture.jpg',
      audio: undefined,
    },
    {
      word: 'Technic',
      translation: 'Техника',
      image: './img/main/technic.jpg',
      audio: undefined,
    },
    {
      word: 'Family',
      translation: 'Семья',
      image: './img/main/family.jpg',
      audio: undefined,
    },
  ],
  animal: [
    {
      word: 'Dog',
      translation: 'Собака',
      image: './img/animal/dog.jpg',
      audio: '1',
    },
    {
      word: 'Cat',
      translation: 'Кошка',
      image: './img/animal/cat.jpg',
      audio: '1',
    },
    {
      word: 'Lion',
      translation: 'Лев',
      image: './img/animal/lion.jpg',
      audio: '1',
    },
    {
      word: 'Wolf',
      translation: 'Волк',
      image: './img/animal/wolf.jpg',
      audio: '1',
    },
    {
      word: 'Elephant',
      translation: 'Слон',
      image: './img/animal/elephant.jpg',
      audio: '1',
    },
    {
      word: 'Snake',
      translation: 'Змея',
      image: './img/animal/snake.jpg',
      audio: '1',
    },
    {
      word: 'Spider',
      translation: 'Паук',
      image: './img/animal/spider.jpg',
      audio: '1',
    },
    {
      word: 'Bear',
      translation: 'Медведь',
      image: './img/animal/bear.jpg',
      audio: '1',
    },
  ],
  clothes: [
    {
      word: 'Hat',
      translation: 'Шляпа',
      image: './img/clothes/hat.jpg',
      audio: '1',
    },
    {
      word: 'Boots',
      translation: 'Ботинки',
      image: './img/clothes/boots.jpg',
      audio: '1',
    },
    {
      word: 'T-shirt',
      translation: 'Футболка',
      image: './img/clothes/t-shirt.jpg',
      audio: '1',
    },
    {
      word: 'Pants',
      translation: 'Штаны',
      image: './img/clothes/pants.jpg',
      audio: '1',
    },
    {
      word: 'Cap',
      translation: 'Кепка',
      image: './img/clothes/cap.jpg',
      audio: '1',
    },
    {
      word: 'Socks',
      translation: 'Носки',
      image: './img/clothes/socks.jpg',
      audio: '1',
    },
    {
      word: 'Jeans',
      translation: 'Джинсы',
      image: './img/clothes/jeans.jpg',
      audio: '1',
    },
    {
      word: 'Dress',
      translation: 'Платье',
      image: './img/clothes/dress.jpg',
      audio: '1',
    },
  ],
  food: [
    {
      word: 'Hamburger',
      translation: 'Гамбургер',
      image: './img/food/hamburger.jpg',
      audio: '1',
    },
    {
      word: 'Bread',
      translation: 'Хлеб',
      image: './img/food/bread.jpg',
      audio: '1',
    },
    {
      word: 'Steak',
      translation: 'Стейк',
      image: './img/food/steak.jpg',
      audio: '1',
    },
    {
      word: 'Pizza',
      translation: 'Пицца',
      image: './img/food/pizza.jpg',
      audio: '1',
    },
    {
      word: 'Cheese',
      translation: 'Сыр',
      image: './img/food/cheese.jpg',
      audio: '1',
    },
    {
      word: 'Eggs',
      translation: 'Яйца',
      image: './img/food/eggs.jpg',
      audio: '1',
    },
    {
      word: 'Mango',
      translation: 'Манго',
      image: './img/food/mango.jpg',
      audio: '1',
    },
    {
      word: 'Sugar',
      translation: 'Сахар',
      image: './img/food/sugar.jpg',
      audio: '1',
    },
  ],
  school: [
    {
      word: 'Teacher',
      translation: 'Учитель',
      image: './img/school/teacher.jpg',
      audio: '1',
    },
    {
      word: 'Students',
      translation: 'Студенты',
      image: './img/school/students.jpg',
      audio: '1',
    },
    {
      word: 'Book',
      translation: 'Книга',
      image: './img/school/book.jpg',
      audio: '1',
    },
    {
      word: 'Pencil',
      translation: 'Карандаш',
      image: './img/school/pencil.jpg',
      audio: '1',
    },
    {
      word: 'Backpack',
      translation: 'Рюкзак',
      image: './img/school/backpack.jpg',
      audio: '1',
    },
    {
      word: 'Ruler',
      translation: 'Линейка',
      image: './img/school/ruler.jpg',
      audio: '1',
    },
    {
      word: 'Pen',
      translation: 'Ручка',
      image: './img/school/pen.jpg',
      audio: '1',
    },
    {
      word: 'Blackboard',
      translation: 'Доска',
      image: './img/school/blackboard.jpg',
      audio: '1',
    },
  ],
  nature: [
    {
      word: 'Forest',
      translation: 'Лес',
      image: './img/nature/forest.jpg',
      audio: '1',
    },
    {
      word: 'Water',
      translation: 'Вода',
      image: './img/nature/water.jpg',
      audio: '1',
    },
    {
      word: 'Sea',
      translation: 'Море',
      image: './img/nature/sea.jpg',
      audio: '1',
    },
    {
      word: 'Sand',
      translation: 'Песок',
      image: './img/nature/sand.jpg',
      audio: '1',
    },
    {
      word: 'Grass',
      translation: 'Трава',
      image: './img/nature/grass.jpg',
      audio: '1',
    },
    {
      word: 'Flame',
      translation: 'Пламя',
      image: './img/nature/flame.jpg',
      audio: '1',
    },
    {
      word: 'Star',
      translation: 'Звезда',
      image: './img/nature/star.jpg',
      audio: '1',
    },
    {
      word: 'Stone',
      translation: 'Камень',
      image: './img/nature/stone.jpg',
      audio: '1',
    },
  ],
  furniture: [
    {
      word: 'Table',
      translation: 'Стол',
      image: './img/furniture/table.jpg',
      audio: '1',
    },
    {
      word: 'Sofa',
      translation: 'Диван',
      image: './img/furniture/sofa.jpg',
      audio: '1',
    },
    {
      word: 'Lamp',
      translation: 'Лампа',
      image: './img/furniture/lamp.jpg',
      audio: '1',
    },
    {
      word: 'Bed',
      translation: 'Кровать',
      image: './img/furniture/bed.jpg',
      audio: '1',
    },
    {
      word: 'Chair',
      translation: 'Стул',
      image: './img/furniture/chair.jpg',
      audio: '1',
    },
    {
      word: 'Stool',
      translation: 'Табуретка',
      image: './img/furniture/stool.jpg',
      audio: '1',
    },
    {
      word: 'Armchair',
      translation: 'Кресло',
      image: './img/furniture/armchair.jpg',
      audio: '1',
    },
    {
      word: 'Wardrobe',
      translation: 'Шкаф(гардероб)',
      image: './img/furniture/wardrobe.jpg',
      audio: '1',
    },
  ],
  technic: [
    {
      word: 'Phone',
      translation: 'Телефон',
      image: './img/technic/phone.jpg',
      audio: '1',
    },
    {
      word: 'Computer',
      translation: 'Компьютер',
      image: './img/technic/computer.jpg',
      audio: '1',
    },
    {
      word: 'Printer',
      translation: 'Принтер',
      image: './img/technic/printer.jpg',
      audio: '1',
    },
    {
      word: 'Camera',
      translation: 'Камера',
      image: './img/technic/camera.jpg',
      audio: '1',
    },
    {
      word: 'Laptop',
      translation: 'Ноутбук',
      image: './img/technic/laptop.jpg',
      audio: '1',
    },
    {
      word: 'Television',
      translation: 'Телевизор',
      image: './img/technic/television.jpg',
      audio: '1',
    },
    {
      word: 'Iron',
      translation: 'Утюг',
      image: './img/technic/iron.jpg',
      audio: '1',
    },
    {
      word: 'Tablet',
      translation: 'Планшет',
      image: './img/technic/tablet.jpg',
      audio: '1',
    },
  ],
  family: [
    {
      word: 'Mom',
      translation: 'Мама',
      image: './img/family/mom.jpg',
      audio: '1',
    },
    {
      word: 'Dad',
      translation: 'Папа',
      image: './img/family/dad.jpg',
      audio: '1',
    },
    {
      word: 'Sister',
      translation: 'Сестра',
      image: './img/family/sister.jpg',
      audio: '1',
    },
    {
      word: 'Brother',
      translation: 'Брат',
      image: './img/family/brother.jpg',
      audio: '1',
    },
    {
      word: 'Grandmother',
      translation: 'Бабушка',
      image: './img/family/grandmother.jpg',
      audio: '1',
    },
    {
      word: 'Grandfather',
      translation: 'Дедушка',
      image: './img/family/grandfather.jpg',
      audio: '1',
    },
    {
      word: 'Twins',
      translation: 'Близнецы',
      image: './img/family/twins.jpg',
      audio: '1',
    },
    {
      word: 'Son',
      translation: 'Сын',
      image: './img/family/son.jpg',
      audio: '1',
    },
  ],
};

export default cards;